path_prepend "$HOME/.local/bin"
path_prepend "$HOME/.dotfiles/bin"
path_prepend "$HOME/.emacs.d/bin"
path_prepend "$HOME/.local/lib/python3.9/site-packages/memacs/"
path_prepend "$HOME/go/bin"
path_prepend "/usr/local/texlive/2023/bin/x86_64-linux/"
path_prepend "$HOME/.local/bin/edirect"
path_prepend "$HOME/Installations/sratoolkit.3.1.1-ubuntu64/bin"
