path_prepend "$HOME/.local/bin"
path_prepend "$HOME/.dotfiles/bin"
path_prepend "$HOME/.emacs.d/bin"
path_prepend "$HOME/.local/lib/python3.9/site-packages/memacs/"
path_prepend "$HOME/go/bin"
path_prepend "/repos/axii/bin"
