#!/usr/bin/env bash

set -e


. ./pre-install.sh
CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"



cd "${BASEDIR}"

setup_hooks ()
{
# Copy the pre-commit hook to the .git/hooks directory
cp hooks/pre-commit .git/hooks/pre-commit
chmod +x .git/hooks/pre-commit

echo "Git hooks have been set up."
}

setup_hooks

git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"



"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

if [ -d "/home/tassilo/" ];then
  echo "Since this is desktop, running home_manager"
  home-manager switch --show-trace
fi



# some helpers and error handling:

# Add systemd timer setup
SYSTEMD_SERVICE_FILE="./config/systemd/user/detault.target.wants/writing_tracker.service"
SYSTEMD_TIMER_FILE="./config/systemd/user/detault.target.wants/writing_tracker.timer"

if [ -f "$SYSTEMD_SERVICE_FILE" ] && [ -f "$SYSTEMD_TIMER_FILE" ]; then
  echo "starting to enable writing_tracker script."
  systemctl --user enable writing-tracker.service
  systemctl --user enable writing-tracker.timer
  systemctl --user start writing-tracker.timer
  echo "Systemd timer enabled and started."
else
  echo "Error: Missing systemd service or timer file."
fi
