#!/usr/bin/env bash
add-apt-repository ppa:regolith-linux/release -y
add-apt-repositoryk
apt update
apt install git -y
apt install neovim -y
apt install minecraft -y
apt install apt -y
apt install curl -y
apt install fzf -y
apt install tldr -y
apt install fd-find -y
apt install redshift
apt install arandr
snap install deja-dup --classic
snap install espanso --classic
apt install ranger
apt install tor-browser
sudo snap install polar-bookshelf

