#!/bin/bash
# Remap Touchpad button map (if TrackPoint is merged)

TOUCHPAD_NAME="ETPS/2 Elantech Touchpad"
TOUCHPAD_ID=$(xinput list --id-only "$TOUCHPAD_NAME")

if [ -n "$TOUCHPAD_ID" ]; then
  xinput set-button-map "$TOUCHPAD_ID" 1 3 2 4 5 6 7
fi
