#!/usr/bin/env bash
unwanted_dir="${HOME}/.dotfiles/config/op"

if [ ! -e "$unwanted_dir" ]; then
    exit 0
fi

if [ -d "$unwanted_dir" ]; then
    echo "Error: Directory $unwanted_dir exists. OnePassword will complain if ~/.config/op is just a softlink."
    echo "Move the directory back before committing."
    exit 1
fi
