# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/hgiesel/Developer/repos/anki_search_bar/designer/searchbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchBar(object):
    def setupUi(self, SearchBar):
        SearchBar.setObjectName("SearchBar")
        SearchBar.resize(604, 50)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SearchBar.sizePolicy().hasHeightForWidth())
        SearchBar.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SearchBar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.close = QtWidgets.QToolButton(SearchBar)
        self.close.setStyleSheet("")
        self.close.setAutoRaise(True)
        self.close.setObjectName("close")
        self.horizontalLayout.addWidget(self.close)
        self.lineEdit = QtWidgets.QLineEdit(SearchBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setText("")
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.next = QtWidgets.QToolButton(SearchBar)
        self.next.setText("")
        self.next.setAutoRaise(True)
        self.next.setArrowType(QtCore.Qt.DownArrow)
        self.next.setObjectName("next")
        self.horizontalLayout.addWidget(self.next)
        self.prev = QtWidgets.QToolButton(SearchBar)
        self.prev.setText("")
        self.prev.setAutoRaise(True)
        self.prev.setArrowType(QtCore.Qt.UpArrow)
        self.prev.setObjectName("prev")
        self.horizontalLayout.addWidget(self.prev)

        self.retranslateUi(SearchBar)
        QtCore.QMetaObject.connectSlotsByName(SearchBar)

    def retranslateUi(self, SearchBar):
        _translate = QtCore.QCoreApplication.translate
        SearchBar.setWindowTitle(_translate("SearchBar", "Form"))
        self.close.setText(_translate("SearchBar", "❌"))
        self.lineEdit.setPlaceholderText(_translate("SearchBar", "Search..."))
