# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
#
# # work with date ISO 8601 easy
# 
# alias isodate="date +%Y-%m-%dT%H:%M:%S%z"
# alias isodate_utc="date -u +%Y-%m-%dT%H:%M:%SZ"
# alias isodate_basic="date -u +%Y%m%dT%H%M%SZ"
# alias unixstamp="date +%s"
# alias date_locale="date +"%c""
matches:
  - trigger: ":fdatetime"
    replace: "{{output}}"
    vars:
    - name: form1
      type: form
      params:
        layout: |
          Which type of input do you want to provide?
          Please enter the date (YYYY-MM-DD) or 2-character weekday shorthand:
          [[value]]
          Please enter the time (HH:MM):
          [[time]]
    - name: output
      type: shell
      params:
        cmd: "python3 /home/tassilo/bin/format_datetime.py '{{form1.value}}' '{{form1.time}}'"
  - trigger: ":unixdate"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "date +%s"
  - trigger: ":ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl 'https://api.ipify.org'"
  # local date
  - trigger: ":ldate"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "date"
          debug: true
  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  #american dates
  - trigger: ":adate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  # Day
  - trigger: ":day"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d"

  # ISO-date
  - trigger: ":isodate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d %H:%M"

  # ISO-time
  - trigger: ":time"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d %H:%M"
  # Dates for OrgMode
  - trigger: ":odate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "[%Y-%m-%d]"
  # latex
  - trigger: "\\pd "
    form: \frac{\partial {{num}}}{\partial {{denum}}}
  - trigger: "\\pdc "
    form: \left(\frac{\partial {{num}}}{\partial {{denum}}}\right)_{{index}}
  - trigger: ":x "
    replace: "$x$"



  - trigger: '@tw'
    replace: 'tassilo.neubauer@web.de'
  - trigger: '@tg'
    replace: 'tassilo.neubauer@gmail.com'
  - trigger: '@up'
    replace: 'upkim@student.kit.edu'
  - trigger: 'gtasse'
    replace: "Grüße\n\nTassilo"
  - trigger: 'mfg'
    replace: "Mit freundlichen Grüßen\n\nTassilo Neubauer"
  - trigger: "ill"
    replace: "i’ll"
    propagate_case: true
    word: true
    
  - trigger: ":TN"
    replace: "Tassilo Neubauer"
  - trigger: ":tn"
    replace: "tassilo neubauer"
  - trigger: ":sws."
    replace: "😅"
  - trigger: "Rn"
    replace: "ℝⁿ"
  - trigger: ":github"
    replace: "git@github.com:sonofhypnos/"
  - trigger: ":windows."
    replace: ""
  - trigger: "moloch"
    replace: "coordination problem"
  - trigger: "agenty"
    replace: "proactive"
  - trigger: "heuristic"
    replace: "rule of thumb"
  - trigger: "order of magnitue"
    replace: "10 times bigger"
  - trigger: "epistemic status"
    replace: "Confidence level"
  - trigger: "viable"
    replace: "practical"
  - trigger: "utilise"
    replace: "use"
  - trigger: "retain"
    replace: "keep"
  - trigger: "irregardless"
    replace: "regardless"
  - trigger: "hitherto"
    replace: "until now"
  - trigger: "henceforth"
    replace: "from now on"
  - trigger: "exhibit"
    replace: "show"
  - trigger: "assidiuously"
    replace: "actively"
  - trigger: "backround"
    replace: "background"
  - trigger: ":fnr"
    replace: '00000050878.5'
  - trigger: ":hg"
    replace: "Herzliche Grüße\nTassilo"
  - trigger: ":hg"
    replace: "Liebe Grüße\nTassilo"
  - trigger: ":gt"
    replace: "Grüße\nTassilo"
  - trigger: "lenght"
    replace: "length"
  - trigger: "compiel"
    replace: "compile"
  - trigger: "tenosr"
    replace: "tensor"
  - trigger: ":HaT:"
    replace: "Grüße\n\nTassilo F504"
  - trigger: ":lw"
    replace: "https://lesswrong.com"
  - trigger: ":vgt"
    replace: "Viele Grüße

Tassilo"
  - trigger: "@ra"
    replace: "rabea.neubauer@outlook.de"
  - trigger: ":CT"
    replace: "Cheers,
Tassilo"
